POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Food Blog",
    "author": "Gordon Ramsay",
    "url": "www.gordonramsay.com",
    "likes": 6144,
    "userId": "615e5d53b56df954a37d6fd6"
}

### DELETE BLOG
DELETE http://localhost:3003/api/blogs/615e59c1217452baf6483edd

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "blogs": [],
    "username": "johhnyboi22",
    "name": "John",
    "password": "password"
}

### DELETE USER
DELETE http://localhost:3003/api/users/615e539e035e3159e6fc60f8
